package com.taotao.pojo;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Id
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    public String[] item = {"Id","name","username","password","auth","address","count","registertime"};
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.auth
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    private String auth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.count
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.registertime
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    private Date registertime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Id
     *
     * @return the value of user.Id
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Id
     *
     * @param id the value for user.Id
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.auth
     *
     * @return the value of user.auth
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    public String getAuth() {
        return auth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.auth
     *
     * @param auth the value for user.auth
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    public void setAuth(String auth) {
        this.auth = auth == null ? null : auth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.count
     *
     * @return the value of user.count
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.count
     *
     * @param count the value for user.count
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.registertime
     *
     * @return the value of user.registertime
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.registertime
     *
     * @param registertime the value for user.registertime
     *
     * @mbg.generated Fri Jun 08 11:05:50 GMT+08:00 2018
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", auth='" + auth + '\'' +
                ", address='" + address + '\'' +
                ", count=" + count +
                ", registertime=" + registertime +
                '}';
    }
}